package com.capgemini.demo.cefla.rewards;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(5e5c6d481ae785288af1e0f55b8963a1)
 */
@org.kie.api.definition.type.Label("Award")
public class Award extends java.lang.Object implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Award amount")
   @org.kie.api.definition.type.Position(0)
   private java.lang.Integer amount;

   @org.kie.api.definition.type.Label("Explanation")
   @org.kie.api.definition.type.Position(1)
   private java.lang.String explanation;

   public Award()
   {
   }

   public java.lang.Integer getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Integer amount)
   {
      this.amount = amount;
   }

   public java.lang.String getExplanation()
   {
      return this.explanation;
   }

   public void setExplanation(java.lang.String explanation)
   {
      this.explanation = explanation;
   }

   public Award(java.lang.Integer amount, java.lang.String explanation)
   {
      this.amount = amount;
      this.explanation = explanation;
   }
}