package com.capgemini.demo.cefla.rewards;

/**
 * This class was automatically generated by the data modeler tool.
 * $HASH(47d73902cb4d266c542979398b730b46)
 */
@org.kie.api.definition.type.Label("Employee")
public class Employee extends java.lang.Object implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Award")
   @org.kie.api.definition.type.Position(2)
   private com.capgemini.demo.cefla.rewards.Award award;

   @org.kie.api.definition.type.Label("Department")
   @org.kie.api.definition.type.Position(1)
   private java.lang.String dept;

   @org.kie.api.definition.type.Label("Name")
   @org.kie.api.definition.type.Position(0)
   private java.lang.String name;

   public Employee()
   {
   }

   public com.capgemini.demo.cefla.rewards.Award getAward()
   {
      return this.award;
   }

   public void setAward(com.capgemini.demo.cefla.rewards.Award award)
   {
      this.award = award;
   }

   public java.lang.String getDept()
   {
      return this.dept;
   }

   public void setDept(java.lang.String dept)
   {
      this.dept = dept;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Employee(com.capgemini.demo.cefla.rewards.Award award,
         java.lang.String dept, java.lang.String name)
   {
      this.award = award;
      this.dept = dept;
      this.name = name;
   }

   public Employee(java.lang.String name, java.lang.String dept,
         com.capgemini.demo.cefla.rewards.Award award)
   {
      this.name = name;
      this.dept = dept;
      this.award = award;
   }
}